name: Tag Version

on:
  push:
    branches:
      - main
      - develop

jobs:
  create-release:
    runs-on: ubuntu-latest

    name: Tag New Version
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      # node dependency cache
      # this is not required but speeds up the process
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            node

      - name: Install JS deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Semantic Release
        run: npm install @semantic-release/gitlab @semantic-release/changelog @semantic-release/git

      - name: Tag Version
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
