name: Tag Version

on:
  push:
    paths-ignore:
      - "src/content/**"
      - "src/lab-modules/**"
      - "public/**"
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    name: Tag New Version
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[release]') &&
      !contains(github.event.head_commit.message, '[content]')

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
      # node dependency cache
      # this is not required but speeds up the process
      - uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            node

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Tag Version
        run: bunx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
